name: Integración Continua

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        whit:
          node-version: 'lts/*'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npm test --silent